CREATE TABLE IF NOT EXISTS `partners` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `password` VARCHAR (12) NOT NULL,
  `member_since` DATE NOT NULL,
  `total_stars` INT UNSIGNED NOT NULL DEFAULT 0,
  `number_stars` INT UNSIGNED NOT NULL DEFAULT 0,
  `path_image` VARCHAR(255) NULL,
  `profile_json` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `applications` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partner_id` SMALLINT NOT NULL,
  `title` VARCHAR(70) NOT NULL DEFAULT '',
  `slug` VARCHAR(50) NOT NULL DEFAULT '',
  `description` TEXT NULL,
  `paid` TINYINT NOT NULL DEFAULT 0,
  `version` VARCHAR(8) NOT NULL DEFAULT '1.0.0',
  `version_date` DATE NULL,
  `type` VARCHAR(14) NULL,
  `module` CHAR(2) NULL,
  `load_events` TEXT NULL,
  `script_uri` VARCHAR(255) NULL,
  `github_repository` VARCHAR(255),
  `authentication` TINYINT NOT NULL DEFAULT 0,
  `auth_callback_uri` VARCHAR(255),
  `auth_scope` TEXT NULL,
  `liked` INT NOT NULL DEFAULT 0,
  `not_liked` INT NOT NULL DEFAULT 0,
  `link_video` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`partner_id`) REFERENCES `partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `themes` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partner_id` SMALLINT NOT NULL,
  `title` VARCHAR(70) NOT NULL DEFAULT '',
  `slug` VARCHAR(50) NOT NULL DEFAULT '',
  `description` TEXT NULL,
  `paid` TINYINT NOT NULL DEFAULT 0,
  `version` VARCHAR(8) NOT NULL DEFAULT '1.0.0',
  `version_date` DATE NULL,
  `liked` INT NOT NULL DEFAULT 0,
  `not_liked` int NOT NULL DEFAULT 0,
  `link_video` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`partner_id`) REFERENCES `partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `plans`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `app_id` MEDIUMINT NOT NULL,
  `store_id` SMALLINT NOT NULL,
  `date_init` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `type_plan` VARCHAR(15) NOT NULL DEFAULT 'trial',
  `app_value` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `payment_status` VARCHAR(15) NOT NULL DEFAULT 'not_confirmed',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`app_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `buy_themes`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `theme_id` MEDIUMINT NOT NULL,
  `store_id` SMALLINT NOT NULL,
  `date_init` DATE NOT NULL,
  `date_end` DATE NULL,
  `type_buy` VARCHAR(15) NOT NULL DEFAULT 'trial',
  `theme_value` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `payment_status` VARCHAR(15) NOT NULL DEFAULT 'not_confirmed',
  PRIMARY KEY(`id`)
  FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `comment_apps`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` SMALLINT NOT NULL,
  `app_id` MEDIUMINT NOT NULL,
  `date_comment` DATE NULL,
  `comment` TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`app_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `comment_themes`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` SMALLINT NOT NULL,
  `theme_id` MEDIUMINT NOT NULL,
  `date_comment` DATE NULL,
  `comment` TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) EXISTING=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `comment_partners`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` SMALLINT NOT NULL,
  `partner_id` SMALLINT NOT NULL,
  `date_comment` DATE NULL,
  `comment` TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`partner_id`) REFERENCES `partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `inbox`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` SMALLINT NOT NULL,
  `partner_id` SMALLINT NOT NULL,
  `date_msg` DATE NULL,
  `msg` TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`partner_id`) REFERENCES `partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `image_apps`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `app_id` MEDIUMINT NOT NULL,
  `name` VARCHAR(50) NULL,
  `path_image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`app_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `image_themes`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `theme_id` MEDIUMINT NOT NULL,
  `name` VARCHAR(50) NULL,
  `path_image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `badges`(
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partner_id` SMALLINT NOT NULL,
  `name` VARCHAR(15) NULL,
  `path_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`partner_id`) REFERENCES `partners`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `category_apps`(
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR (20) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `relationship_category_apps`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `app_id` MEDIUMINT NOT NULL,
  `category_apps_id` MEDIUMINT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`app_id`) REFERENCES `applications`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (`category_apps_id`) REFERENCES `category_apps`(`id`) on DELETE CASCADE on UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `category_themes`(
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR (20) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `relationship_category_themes`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `theme_id` MEDIUMINT NOT NULL,
  `category_themes_id` MEDIUMINT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`theme_id`) REFERENCES `themes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (`category_themes_id`) REFERENCES `category_themes`(`id`) on DELETE CASCADE on UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;
